

from pcap_constants import LIST_LENGTH
# see data_features_type.pxd for note about unused alignment padding
DATA_FEATURES_DTYPE = [
                       ("key", "i8"),
                       ("ip_protocol", "u1"),
                       ("unused_alignment_padding_1", "u1"),
                       ("unused_alignment_padding_2", "u1"),
                       ("unused_alignment_padding_3", "u1"),
                       ("ip_nps", "u4"),
                       ("ip_other", "u4"),
                       ("port_nps", "u2"),
                       ("port_other", "u2"),
                       ("int_in_packets", "u8"),
                       ("int_in_bytes", "u8"),
                       ("int_out_packets", "u8"),
                       ("int_out_bytes", "u8"),
                       ("begin_timestamp", "f8"),
                       ("end_timestamp", "f8"),
                       ("in_packets", "f4"),
                       ("in_bytes", "f4"),
                       ("in_mean_packet_length", "f4"),
                       ("in_packets_per_second", "f4"),
                       ("in_bytes_per_second", "f4"),
                       ("out_packets", "f4"),
                       ("out_bytes", "f4"),
                       ("out_mean_packet_length", "f4"),
                       ("out_packets_per_second", "f4"),
                       ("out_bytes_per_second", "f4"),
                       ("t_duration", "f4"),
                       ("list_in_packets", "f4"),
                       ("list_in_bytes", "f4"),
                       ("list_in_mean_packet_length", "f4"),
                       ("list_in_packets_per_second", "f4"),
                       ("list_in_bytes_per_second", "f4"),
                       ("list_out_packets", "f4"),
                       ("list_out_bytes", "f4"),
                       ("list_out_mean_packet_length", "f4"),
                       ("list_out_packets_per_second", "f4"),
                       ("list_out_bytes_per_second", "f4"),
                       ("list_t_duration", "f4"),
                       ("flow_types", "(%d,)f4"%LIST_LENGTH),
                       ("delta_timestamps", "(%d,)f4"%LIST_LENGTH),
                       ("packet_lengths", "(%d,)f4"%LIST_LENGTH),
                      ]

