cdef extern from "pcap_constants.h":
    cdef const Py_ssize_t C_LIST_LENGTH
    cdef const Py_ssize_t C_FLOW_TYPE_INSIDE_ONLY
    cdef const Py_ssize_t C_FLOW_TYPE_OUTSIDE_ONLY
    cdef const Py_ssize_t C_FLOW_TYPE_OUTGOING
    cdef const Py_ssize_t C_FLOW_TYPE_INCOMING
    cdef const Py_ssize_t C_FLOW_TYPE_UNIDENTIFIED

LIST_LENGTH = C_LIST_LENGTH
FLOW_TYPE_INSIDE_ONLY = C_FLOW_TYPE_INSIDE_ONLY 
FLOW_TYPE_OUTSIDE_ONLY = C_FLOW_TYPE_OUTSIDE_ONLY 
FLOW_TYPE_OUTGOING = C_FLOW_TYPE_OUTGOING 
FLOW_TYPE_INCOMING = C_FLOW_TYPE_INCOMING 
FLOW_TYPE_UNIDENTIFIED = C_FLOW_TYPE_UNIDENTIFIED 

